/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostal_management_system;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author laxmi
 */
public class roompayments extends javax.swing.JFrame {

    /**
     * 
     */
    public roompayments() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        txtstudntid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "student id", "name", "amount remain"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 77, 307, 527));

        jButton3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton3.setText("Refresh Table");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 143, -1, 33));

        txtstudntid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudntidActionPerformed(evt);
            }
        });
        jPanel2.add(txtstudntid, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 286, 143, 31));

        jButton2.setText("Get payments");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 364, -1, 40));

        jLabel2.setForeground(new java.awt.Color(44, 128, 120));
        jLabel2.setText("Student ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 286, 74, 31));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 6, -1, -1));

        jButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton1.setText("Get payments from all");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 208, 199, 31));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(86, 115, 152));
        jLabel3.setText("Students who need to pay");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 14, -1, 27));

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int a,b,c,d;

        try {

           String myUrl = Utils.myUrl;
            java.sql.Connection conn = DriverManager.getConnection(myUrl, Utils.user, Utils.pass);

            try ( //first we change paidOrNot to 0 ,cause this is a new month and we need to get payments from all
                Statement st = conn.createStatement()) {
                String query2 ="update student set paidOrNot =0 ";

                st.execute(query2);

                //now we are gonna get payements from all the guys who have money in thair accounts

                String querygetid ="SELECT student_id FROM reservation ;";

                //create the java statement

                // execute the query, and get a java result set
                ResultSet rs2 = st.executeQuery(querygetid);

                while (rs2.next())
                {
                    int idOfstudent= rs2.getInt("student_id");//this will give us all the students id's to us
                    System.out.println(idOfstudent);
                    //now we are going to get their room type

                    //********room type

                    getpay x = new getpay();
                    int y=x.getroomtype(idOfstudent);

                    System.out.println(y);//now we know their id and room type  so lets get mmmm price for room id

                    //********payment for the room
                    int roompricee = x.getroomprice(y, 8000, 15000);

                    System.out.println(roompricee);//now we know how much he need to pay for the room
                    // now we need his balace to check he can pay or not

                    int studentacbal=x.getbalanceofaccount(idOfstudent);
                    System.out.println(studentacbal);
                    // now we are going to get payments from all who have money to do it so i am gonna call getpaymentsfromall method

                    if(studentacbal>roompricee){

                        x.getpaymentsfromall(roompricee,studentacbal,idOfstudent);

                    }

                    //

                }}

            }
            catch (SQLException e)
            {
                System.err.println("Got an exception! ");
                System.err.println(e.getMessage());
            }

            // TODO add your handling code here:
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int studentid=Integer.parseInt(txtstudntid.getText());

        getpay m = new getpay();

        int check=m.checkpaidOrnot(studentid);

        if(check==0){
            //********room type

            int y=m.getroomtype(studentid);

            System.out.println(y);//now we know their id and room type  so lets get mmmm price for room id

            //********payment for the room
            int roompricee = m.getroomprice(y, 8000, 15000);

            System.out.println(roompricee);//now we know how much he need to pay for the room
            // now we need his balace to check he can pay or not

            int studentacbal=m.getbalanceofaccount(studentid);
            System.out.println(studentacbal);
            // now we are going to get payments from all who have money to do it so i am gonna call getpaymentsfromall method

            if(studentacbal>roompricee){

                m.getpaymentsfromall(roompricee,studentacbal,studentid);

            }

            else {

                JOptionPane.showMessageDialog(null, "need to pay");

            }

        }

        else {

            JOptionPane.showMessageDialog(null, "already paid");

        }

    }

    private void txtstudntidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudntidActionPerformed
        // TODO add your handling code here:
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        // dispose(); //Destroy the JFrame object

        roompayments rm = new roompayments();
        this.dispose();
        rm. showtable1();
        rm.setVisible(true);
        rm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        
        
    }
    
    
   
     
    private void showtable1(){
     

     try {

            String myUrl = Utils.myUrl;
            java.sql.Connection conn = DriverManager.getConnection(myUrl, Utils.user, Utils.pass);

            String query ="SELECT * FROM student where paidOrNot=0;";

            //create the java statement
            Statement st = conn.createStatement();
            // execute the query, and get a java result set
            ResultSet rs = st.executeQuery(query);

            while (rs.next())
            {
                int p= rs.getInt("id");
                String q=rs.getString("name");
               
                String id=Integer.toString(p);
                String name=q;

                String tbData[]={id,name};

                DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();

                tblModel.fireTableDataChanged();
                tblModel.addRow(tbData);

            }
            st.close();
        }
        catch (Exception e)
        {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
 
     
     
    
     
     
     
     }
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(roompayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(roompayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(roompayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(roompayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new roompayments().setVisible(true);
            }
        });
    }

    
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtstudntid;
    
}
